---
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@cfdb3cce90daece912e6a5cb3f20b2316a78a5bf # v0.1.0-alpha.31
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      max-parallel: 4
      matrix:
        node-version: ["24"]

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn test:unit:ci

      - run: yarn test:e2e:ci
        continue-on-error: true # e2e tests seem to fail randomly on CI

  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    strategy:
      max-parallel: 4
      matrix:
        node-version: ["24"]

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn lint

  audit:
    runs-on: ubuntu-latest
    name: Node Audit
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["24"]

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn npm audit
        continue-on-error: true # allow the workflow to continue even if there are vulnerabilities, npm audit often shows problems

  cyclonedx:
    runs-on: ubuntu-latest
    name: SBOM
    permissions:
      contents: read
      security-events: write
    strategy:
      max-parallel: 4
      matrix:
        node-version: ["24"]

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn cyclonedx

      - uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7
        id: anchore
        with:
          sbom: .quasar/sbom.json
          fail-build: false # we can skip this as informational only, in a production environment we would want to fail the build
          severity-cutoff: medium
      - uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4
        with:
          sarif_file: ${{ steps.anchore.outputs.sarif }}
        continue-on-error: true # the anchore/scan-action sometimes generates an invalid sarif file here; hence, we continue on error

  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
          scandir: ./deploy
          format: gcc

      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
          scandir: ./deploy
          format: diff

  build:
    runs-on: ubuntu-latest
    name: Build SPA
    needs:
      - test
      - eslint
      - audit
      - cyclonedx
    strategy:
      max-parallel: 4
      matrix:
        node-version: ["24"]

    steps:
      - uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable

      - run: yarn build
